### ISSUE TITLE
Ukol c.1

### ISSUE THREAD

**Issue by VeronikaDolan** [VeronikaDolan/python-kurz-2022-ukoly#1]
Odevzdávám úkol č. 1.

https://github.com/VeronikaDolan/python-kurz-2022-ukoly/blob/fba58d42be2816ad21182a1bffed7a668a96f6e5/ukol-1.py

**Comment by syzonyuliia** [comment]
Super, výborně, issue a řešení vypadají dobře. Chválím i rychlé odevzdání.

**Comment by syzonyuliia** [comment]
Mám jediné maličké vylepšení. Výraz `True == baliky[kod]` vrácí `True` nebo `False` a jeho hodnota je vždy stejná jako hodnota samotného výrazu `baliky[kod]`. Takže v tomto případě by bylo postačující napsat `if baliky[kod]:`
