### ISSUE TITLE
Odevzdání úkolu č. 3

### ISSUE THREAD

**Issue by VeronikaDolan** [VeronikaDolan/python-kurz-2022-ukoly#3]
Ahoj,

odevzdávám úkol č. 3.

https://github.com/VeronikaDolan/python-kurz-2022-ukoly/blob/9a2c91b620289e851d28598b9fb6a74e170bc25f/ukol-3.py

Hezký den :-)

Verča Dolanová

**Comment by VeronikaDolan** [comment]
Jo, a je to včetně bonusu, to jsem uzapoměla říct :-)

**Comment by pmoravkova** [comment]
hodne dobry reseni. Gratuluji, vazne pekne. A super i pouziti sys.exit()
Super by bylo jeste, kdybys treba i tohle hodila do te funkce, co kontroluje cislo. Ciste teoreticky ma cislo bud devet cislic, nebo 13 a zaroven na zacatku +420.
```
number = number.replace(' ','') #...maze mezery v tel.cisle

#...kontrola formatu cisla (pred funkci zkontroluje delku telefonniho cisla a pokud je nespravna ukonci program)
if format == False: #...pokud je vysledek funkce valid_number False
    print('Spatne zadany format telefonniho cisla!')
    sys.exit()

#...kontrola predvolby (pred funkci zkontroluje predvolbu a pokud je nespravna ukonci program)
if number[0:4] !='+420': #...pokud prvni 4 pozice nejsou v zadanem formatu
    print('Zadal jsi nespravnou predvolbu!')
    sys.exit()
```
Tip: do sys.exit() se da napsat zprava. Casto se tam pisi cisla, abychom vedeli, ze kdyz cislo neni integer napr., tak se da jeden ciselny kod klidne do vice sys.exitu atd. Takze klidne muzes udelat i:
```
if not format: # da se pouzit not namisto == False
    sys.exit('Spatne zadany format telefonniho cisla!') # a tohle se da pouzit namisto printu.
```
